{% set name = "azure-storage-file" %}
{% set version = "2.1.0" %}
{% set sha256 = "3559b9c7ab13450c66ea833eb82c28233bee24f1bd8ca19aa7d27f8c23d5bc53" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - azure-common >=1.1.5
    - azure-storage-common >=2.1,<3.0

test:
  imports:
    - azure
    - azure.storage
    - azure.storage.file
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Azure/azure-storage-python
  license: Apache-2.0
  license_family: Apache
  license_file: {{ RECIPE_DIR }}/LICENSE.txt
  summary: Microsoft Azure Storage File Client Library for Python

extra:
  recipe-maintainers:
    - xhochy
    - xylar
